site_name: FIWARE Marketplace
site_url: https://fiware-marketplace.readthedocs.org
repo_url: https://github.com/FIWARE-Ops/Marketplace
site_description: FIWARE Marketplace documents
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
extra_css: ['https://fiware.org/style/fiware_readthedocs.css', 'https://fiware.org/style/fiware_readthedocs_neutral.css']

pages:
  - Home: index.md
  - Powered by FIWARE solution:
      - 'How to Apply': solution/apply.md
      - 'Guideline': solution/guideline.md
  - Powered by FIWARE platform:
      - 'How to Apply': platform/apply.md
      - 'Guideline': platform/guideline.md
  - FIWARE-Ready IoT device:
      - 'How to Apply': 'device/apply.md'
      - 'Guideline': 'device/guideline.md'
  - FIWARE-Ready software enabler:
      - 'How to Apply': 'enabler/apply.md'
      - 'Guideline': 'enabler/guideline.md'
  - FIWARE Consulting, Integration and Technical Support Service:
      - 'How to Apply': 'consulting/apply.md'
      - 'Guideline': 'consulting/guideline.md'
  - FIWARE Training and Coaching Service:
      - 'How to Apply': 'training/apply.md'
      - 'Guideline': 'training/guideline.md'
