site_name: FIWARE-ready IoT Devices Program
site_url: https://fiware-ready-iot-device-validation.readthedocs.org
repo_url: https://github.com/FIWARE-Ops/docs.FIWARE-ready-IoT-Devices-Validation
site_description: FIWARE-ready IoT Devices Validation documents
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - Home: "index.md"
