site_name: FIWARE-Ready IoT Device Program
site_url: https://fiware-ready-iot-device-validation.readthedocs.org
repo_url: https://github.com/FIWARE-Ops/docs.FIWARE-ready-IoT-Devices-Validation
site_description: FIWARE-Ready IoT Device Validation documents
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://fiware.org/style/fiware_readthedocs_neutral.css"]
pages:
  - Home: "index.md"
  - "How to Apply": "apply.md" 
  - "Infrastructure": "infrastructure.md"
  - "Testing": "test.md"
  - "Postman Examples": "postman.md"
